# Generated by Django 2.2.5 on 2019-10-23 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_lise_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='lise_users',
            new_name='like_users',
        ),
    ]
